[0m11:12:43.169250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002263C28D4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002263D54CE80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002263D54CC70>]}


============================== 11:12:43.180762 | 2c7ce666-ac05-4eae-9948-b45825fd4469 ==============================
[0m11:12:43.180762 [info ] [MainThread]: Running with dbt=1.10.6
[0m11:12:43.181763 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jiawe\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init netflix', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:12:43.225557 [debug] [MainThread]: Starter project path: C:\Users\jiawe\OneDrive\Desktop\netflixdbt\.venv\lib\site-packages\dbt\include\starter_project
[0m11:12:43.243542 [info ] [MainThread]: 
Your new dbt project "netflix" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:12:43.244472 [info ] [MainThread]: Setting up your profile.
[0m11:18:35.619213 [info ] [MainThread]: Profile netflix written to C:\Users\jiawe\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:18:35.653020 [debug] [MainThread]: Command `dbt init` succeeded at 11:18:35.651018 after 352.70 seconds
[0m11:18:35.659132 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002263C28D4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002263D54CF40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002263D54CE80>]}
[0m11:18:35.663133 [debug] [MainThread]: Flushing usage events
[0m11:18:36.244028 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:39:51.471988 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA7FE1D520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA0124CFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA0124CD90>]}


============================== 13:39:51.479144 | d809075d-ffc5-4902-a260-b5179133dfa8 ==============================
[0m13:39:51.479144 [info ] [MainThread]: Running with dbt=1.10.6
[0m13:39:51.480153 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jiawe\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:39:51.481155 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jiawe\OneDrive\Desktop\netflixdbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:39:51.483665 [debug] [MainThread]: Command `dbt run` failed at 13:39:51.483665 after 0.12 seconds
[0m13:39:51.484672 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA7FE1D520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA0124CD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA0124CBB0>]}
[0m13:39:51.484672 [debug] [MainThread]: Flushing usage events
[0m13:39:51.967018 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:47:51.281185 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020CF10DD4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020CF3371BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020CF3371E20>]}


============================== 08:47:51.286696 | 54f20838-d5a2-4370-8dc1-b6663eb55d35 ==============================
[0m08:47:51.286696 [info ] [MainThread]: Running with dbt=1.10.6
[0m08:47:51.288714 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jiawe\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run -model dim_movie_with_tags', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:47:51.288714 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jiawe\OneDrive\Desktop\netflixdbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:47:51.290710 [debug] [MainThread]: Command `dbt run` failed at 08:47:51.289710 after 0.13 seconds
[0m08:47:51.290710 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020CF10DD4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020CF3371E20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020CF3371AF0>]}
[0m08:47:51.290710 [debug] [MainThread]: Flushing usage events
[0m08:47:51.790891 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:48:30.346056 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FF1560D4F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FF178A1BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FF178A1E50>]}


============================== 08:48:30.349154 | 1da28dbe-bb4a-49d2-b392-440ed33c5b21 ==============================
[0m08:48:30.349154 [info ] [MainThread]: Running with dbt=1.10.6
[0m08:48:30.350475 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jiawe\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run -model dim_movies_with_tags', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:48:30.350475 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jiawe\OneDrive\Desktop\netflixdbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:48:30.352480 [debug] [MainThread]: Command `dbt run` failed at 08:48:30.352480 after 0.11 seconds
[0m08:48:30.352480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FF1560D4F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FF178A1E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FF178A1AF0>]}
[0m08:48:30.352480 [debug] [MainThread]: Flushing usage events
[0m08:48:30.804481 [debug] [MainThread]: An error was encountered while trying to flush usage events
